#!/usr/bin/env python3
"""
Generate environment files for WebReport from config.toml.
"""
import os
import sys
from pathlib import Path
from typing import cast

from sqlalchemy.engine import make_url

# Add parent directory to path to import bd_shared package
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from bd_shared.config import get_config

config = cast(dict[str, object], get_config())
database_config = cast(dict[str, object], config["database"])
webreport_config = cast(dict[str, object], config["webreport"])
xlsm_fetch_config = cast(dict[str, object], config["xlsm_fetch"])
docker_database_url = make_url(cast(str, database_config["docker_url"]))
database_name = docker_database_url.database
database_user = docker_database_url.username
database_password = docker_database_url.password
env_directory = Path(__file__).resolve().parent

if not database_name:
    raise ValueError("database.docker_url must include a database name")
if not database_user:
    raise ValueError("database.docker_url must include a username")
if not database_password:
    raise ValueError("database.docker_url must include a non-empty password")


def dotenv_quote(value: str) -> str:
    return "'" + value.replace("'", "\\'") + "'"


def write_env_file(file_name: str, values: dict[str, str]) -> None:
    content = "# Generated by generate_env.py; do not edit.\n"
    content += "".join(f"{name}={value}\n" for name, value in values.items())
    file_path = env_directory / file_name
    file_descriptor = os.open(
        file_path,
        os.O_WRONLY | os.O_CREAT | os.O_TRUNC,
        0o600,
    )
    fchmod = getattr(os, "fchmod", None)
    if fchmod is not None:
        fchmod(file_descriptor, 0o600)
    with os.fdopen(file_descriptor, "w", encoding="utf-8") as env_file:
        _ = env_file.write(content)


debug = str(cast(bool, webreport_config.get("debug", False))).lower()
reload_enabled = str(cast(bool, webreport_config.get("reload", True))).lower()
env_files: dict[str, dict[str, str]] = {
    ".env": {
        "WEBREPORT_BACKEND_PORT": str(
            cast(int, webreport_config.get("backend_port", 28000))
        ),
        "WEBREPORT_FRONTEND_PORT": str(
            cast(int, webreport_config.get("frontend_port", 28501))
        ),
    },
    ".env.mysql": {
        "MYSQL_DATABASE": dotenv_quote(database_name),
        "MYSQL_USER": dotenv_quote(database_user),
        "MYSQL_PASSWORD": dotenv_quote(database_password),
        "MYSQL_ROOT_PASSWORD": dotenv_quote(database_password),
    },
    ".env.backend": {
        "BD_DOCKER": "true",
        "WEBREPORT_DEBUG": debug,
        "WEBREPORT_RELOAD": reload_enabled,
        "WEBREPORT_BACKEND_DEBUG_PORT": str(
            cast(int, webreport_config.get("backend_debug_port", 5678))
        ),
    },
    ".env.data_collector": {
        "BD_DOCKER": "true",
        "TZ": dotenv_quote(
            cast(str, xlsm_fetch_config.get("timezone", "Europe/Belgrade"))
        ),
    },
    ".env.frontend": {
        "API_BASE_URL": dotenv_quote("http://backend:8000"),
        "CHAT_REQUEST_TIMEOUT_SECONDS": str(
            cast(int, webreport_config["chat_request_timeout_seconds"])
        ),
        "WEBREPORT_DEBUG": debug,
        "WEBREPORT_RELOAD": reload_enabled,
        "WEBREPORT_FRONTEND_DEBUG_PORT": str(
            cast(int, webreport_config.get("frontend_debug_port", 5679))
        ),
    },
    ".env.litellm": {
        "OPENAI_API_KEY": dotenv_quote(
            cast(str, webreport_config.get("openai_api_key", ""))
        ),
        "OPENROUTER_API_KEY": dotenv_quote(
            cast(str, webreport_config.get("openrouter_api_key", ""))
        ),
        "OPENCODE_API_KEY": dotenv_quote(
            cast(str, webreport_config.get("opencode_api_key", ""))
        ),
    },
}

for env_file_name, env_values in env_files.items():
    write_env_file(env_file_name, env_values)

print("Generated environment files: " + ", ".join(env_files))
