import os
import runpy
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


class GenerateEnvTests(unittest.TestCase):
    def test_generates_env_files_when_fchmod_is_unavailable(self) -> None:
        # Given: a copy of the generator on a platform without os.fchmod.
        source_script = Path(__file__).with_name("generate_env.py")
        with tempfile.TemporaryDirectory() as temp_directory:
            script = Path(temp_directory) / source_script.name
            _ = shutil.copyfile(source_script, script)
            sys.path.insert(0, str(Path(__file__).parent.parent))
            fchmod = getattr(os, "fchmod", None)
            if fchmod is not None:
                delattr(os, "fchmod")

            try:
                # When: environment generation runs through the script entry point.
                _ = runpy.run_path(str(script), run_name="__main__")
            finally:
                _ = sys.path.pop(0)
                if fchmod is not None:
                    setattr(os, "fchmod", fchmod)

            # Then: every expected environment file is generated.
            self.assertEqual(
                {path.name for path in Path(temp_directory).glob(".env*")},
                {
                    ".env",
                    ".env.backend",
                    ".env.data_collector",
                    ".env.frontend",
                    ".env.litellm",
                    ".env.mysql",
                },
            )

    def test_generates_litellm_key_from_toml_without_shell_export(self) -> None:
        # Given: an isolated TOML config with an API key and no shell key.
        source_script = Path(__file__).with_name("generate_env.py")
        source_config = Path(__file__).parent.parent / "bd_shared" / "config.toml"
        with tempfile.TemporaryDirectory() as temp_directory:
            script = Path(temp_directory) / source_script.name
            config_path = Path(temp_directory) / "config.toml"
            _ = shutil.copyfile(source_script, script)
            _ = config_path.write_text(
                source_config.read_text(encoding="utf-8").replace(
                    'openai_api_key = ""',
                    'openai_api_key = "config-test-key"',
                ),
                encoding="utf-8",
            )
            environment = os.environ.copy()
            environment["BD_CONFIG_FILE"] = str(config_path)
            _ = environment.pop("OPENAI_API_KEY", None)
            environment["PYTHONPATH"] = str(Path(__file__).parent.parent)

            # When: the generator runs without an exported OPENAI_API_KEY.
            completed = subprocess.run(
                [sys.executable, str(script)],
                cwd=temp_directory,
                env=environment,
                capture_output=True,
                text=True,
            )

            # Then: LiteLLM receives the key supplied by the TOML config.
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertEqual(
                (Path(temp_directory) / ".env.litellm").read_text(encoding="utf-8"),
                "# Generated by generate_env.py; do not edit.\n"
                + "OPENAI_API_KEY='config-test-key'\n",
            )


if __name__ == "__main__":
    _ = unittest.main()
