"""shorting team_name to support mysql key length limitation

Revision ID: 83570ad125de
Revises: 1ec78e9e5d04
Create Date: 2025-09-01 20:17:18.986912

"""
from typing import Sequence, Union
import importlib.util
import os

from alembic import op
import sqlalchemy as sa

# Import functions from previous migration to reuse view creation/deletion logic
# Using importlib because the filename starts with a number
migration_file = "1ec78e9e5d04_create_team_game_scores_view.py"
migration_path = os.path.join(os.path.dirname(__file__), migration_file)
spec = importlib.util.spec_from_file_location("view_migration_module", migration_path)
view_migration = importlib.util.module_from_spec(spec)
spec.loader.exec_module(view_migration)

# Import the functions we need
create_view = view_migration.upgrade
drop_view = view_migration.downgrade


# revision identifiers, used by Alembic.
revision: str = '83570ad125de'
down_revision: Union[str, None] = '1ec78e9e5d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the view first to avoid conflicts with table alteration
    drop_view()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('team_name',
               existing_type=sa.String(length=1024),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###

    # Recreate the view using the previous migration's upgrade function
    create_view()


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the view first
    drop_view()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('team_name',
               existing_type=sa.String(length=256),
               type_=sa.String(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###

    # Recreate the view
    create_view()
